### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by craigsapp** [humdrum-tools/vhv-documentation#23]
The Spanish translation on this page is actually English.

https://github.com/humdrum-tools/vhv-documentation/blob/master/commands/alt-shift-l/index-ES.md

**Comment by davidrizo** [comment]
I have it locally translated. I don't know why it's not uploaded. I'll do it

**Comment by davidrizo** [comment]
Sorry, I see the confusion. I have alt-shift-I (i), not l (L)

**Comment by craigsapp** [comment]
A font problem :-)

**Comment by craigsapp** [comment]
You could put an update in the primary branch (I don't think the language-specific branches are very useful: translations are in their own files so there is minimal change of a version conflict with other languages or the primary branch).

**Comment by davidrizo** [comment]
Done. @craigsapp Close the issue if it is correctly amended

**Comment by craigsapp** [comment]
¡Bueno!:

https://doc.verovio.humdrum.org/commands/alt-shift-l/index-ES.html
