### ISSUE TITLE
Digitacióm

### ISSUE THREAD

**Issue by craigsapp** [humdrum-tools/vhv-documentation#24]
Para el título de esta página:
https://doc.verovio.humdrum.org/humdrum/fingering/index-ES.html

Nunca he escuchado la palabra "digitacióm", ¿probablemente te refieres a "digitación"?

Puedo cambiarlo a "digitación" si eso es correcto.

**Comment by davidrizo** [comment]
Sí, es una errata, es "digitación"

**Comment by davidrizo** [comment]
Corregido
